# This is a basic workflow to help you get started with Actions

name: Fetch Upstream

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *
    # 每隔6小时
jobs:
  openwrt_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: kenzok8/openwrt-packages  # 上游仓库
          target_repository: kld-backups/openwrt-packages  # 你要推送的仓库
          upstream_branch: master  # 默认是拉取上游仓库的master分支
          target_branch: main  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
  lede:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: coolsnowwolf/lede  # 上游仓库
          target_repository: kld-backups/lede  # 你要推送的仓库
          upstream_branch: master  # 默认是拉取上游仓库的master分支
          target_branch: main  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
  lede:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: dashingsoft/pyarmor  # 上游仓库
          target_repository: kld-backups/pyarmor  # 你要推送的仓库
          upstream_branch: master  # 默认是拉取上游仓库的master分支
          target_branch: main  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags

